### ISSUE TITLE
RISING is an invalid parameter to esp_sleep_enable_ext0_wakeup

### ISSUE THREAD

**Issue by smhc** [G6EJD/ESP32-Push-button-or-Pulse-Wake-up#1]
```
 esp_sleep_enable_ext0_wakeup((gpio_num_t)GPIO_NUM_12, RISING);
```

I believe the RISING (0x01) being passed here is actually https://docs.espressif.com/projects/esp-idf/en/v5.2.2/esp32/api-reference/system/sleep_modes.html#_CPPv4N28esp_sleep_ext1_wakeup_mode_t24ESP_EXT1_WAKEUP_ANY_HIGHE

https://github.com/espressif/esp-idf/blob/v5.3.1/components/esp_hw_support/include/esp_sleep.h#L38

which is quite different to RISING.

**Comment by G6EJD** [comment]
The RTC IO module is enabled in this mode, so internal pullup or pulldown resistors can also be used. They need to be configured by the application using rtc_gpio_pullup_en() and rtc_gpio_pulldown_en() functions before calling esp_deep_sleep_start() and has been correctly implemented.
